/* confdefs.h */
#define PACKAGE_NAME "plan"
#define PACKAGE_TARNAME "plan"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "plan 1.0"
#define PACKAGE_BUGREPORT "joaqimpla@gmail.com"
#define PACKAGE_URL ""
#define PACKAGE "plan"
#define VERSION "1.0"
#define USE_GL3 "true"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_LIBGLFW 1
#define HAVE_LIBGL 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GLFW_GLFW3_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
